import type { MapData } from './types';
import { project, ProjectionConfig, DEFAULT_PROJECTION } from './projection';
import { buildCorridors, waypointOffset } from './corridors';
import { stadiumForStation } from './stadium';
import { placeLabels } from './layout';

const LINE_WIDTH = 6.5;
const STATION_R = 5;
const INTERCHANGE_R = 8.5;
const TERMINAL_R = 6.5;

export interface ExportOptions {
  /** width attribute on the root svg. viewBox is computed automatically. */
  width?: number;
  /** padding around content in screen px on each side. */
  padding?: number;
  /** include grid lines on each plane (useful for editing reference). */
  showGrid?: boolean;
  /** include the legend block. */
  showLegend?: boolean;
  /** include title and subtitle. */
  showTitle?: boolean;
  title?: string;
  subtitle?: string;
}

const DEFAULTS: Required<ExportOptions> = {
  width: 1500,
  padding: 100,
  showGrid: false,
  showLegend: true,
  showTitle: true,
  title: 'Untitled Transit Map',
  subtitle: 'Generated by iso-metro',
};

/**
 * full svg renderer. parallel corridor offsets, stadium interchanges,
 * auto-placed labels, and css theme variables. matches the python
 * reference renderer.
 */
export function exportSvg(
  data: MapData,
  options: ExportOptions = {},
  cfg: ProjectionConfig = DEFAULT_PROJECTION,
): string {
  const opts = { ...DEFAULTS, ...options };
  const corridors = buildCorridors(data.lines);
  const labels = placeLabels(data, corridors, cfg);

  // collect all projected points to compute viewbox
  const allPts: Array<[number, number]> = [];
  for (const ln of data.lines) {
    for (let i = 0; i < ln.waypoints.length; i++) {
      const o = waypointOffset(ln, i, corridors);
      const p = project(
        ln.waypoints[i].gx + o.x,
        ln.waypoints[i].gy + o.y,
        ln.waypoints[i].plane, cfg);
      allPts.push([p.x, p.y]);
    }
  }
  for (const st of data.stations) {
    const p = project(st.gx, st.gy, st.plane, cfg);
    allPts.push([p.x, p.y]);
  }
  if (allPts.length === 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"/>`;
  }
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const [x, y] of allPts) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  minX -= opts.padding; maxX += opts.padding;
  minY -= opts.padding; maxY += opts.padding;
  const vbw = maxX - minX, vbh = maxY - minY;

  const out: string[] = [];
  out.push(
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `viewBox="${fmt(minX)} ${fmt(minY)} ${fmt(vbw)} ${fmt(vbh)}" ` +
    `width="${opts.width}" font-family="Inter, Helvetica, Arial, sans-serif">`
  );

  // css theme
  const lineVarDecls = data.lines
    .map(l => `    --line-${l.id}: ${l.color};`)
    .join('\n');
  out.push('<defs><style><![CDATA[');
  out.push(`:root {
    --paper: #faf8f3;
    --plane-stroke: #cdbf9c;
    --station-fill: #ffffff;
    --station-stroke: #111111;
    --label-text: #1a1a1a;
    --leader: #777777;
    --lift: #3a3a3a;
${lineVarDecls}
}`);
  out.push(']]></style></defs>');

  // background
  out.push(
    `<rect x="${fmt(minX)}" y="${fmt(minY)}" width="${fmt(vbw)}" ` +
    `height="${fmt(vbh)}" fill="var(--paper, #faf8f3)"/>`
  );

  // planes
  const tints = ['#f0eadf', '#ece5d6', '#e8e0cd', '#e2d8b8', '#dcce a8'];
  data.planes.forEach((p, i) => {
    const tint = tints[i % tints.length];
    const corners = [[-9, -6], [9, -6], [9, 7], [-9, 7]] as const;
    const projected = corners.map(c => project(c[0], c[1], i, cfg));
    const pts = projected.map(s => `${fmt(s.x)},${fmt(s.y)}`).join(' ');
    out.push(
      `<polygon points="${pts}" fill="${tint}" ` +
      `stroke="var(--plane-stroke, #cdbf9c)" stroke-width="0.6" opacity="0.6"/>`
    );
  });

  // lifts under lines
  for (const lf of data.lifts) {
    const a = project(lf.a.gx, lf.a.gy, lf.a.plane, cfg);
    const b = project(lf.b.gx, lf.b.gy, lf.b.plane, cfg);
    out.push(
      `<line x1="${fmt(a.x)}" y1="${fmt(a.y)}" ` +
      `x2="${fmt(b.x)}" y2="${fmt(b.y)}" ` +
      `stroke="var(--lift, #3a3a3a)" stroke-width="2.4" ` +
      `stroke-dasharray="3.5,3" stroke-linecap="round"/>`
    );
  }

  // lines with parallel offsets
  for (const ln of data.lines) {
    if (ln.waypoints.length < 2) continue;
    const points = ln.waypoints.map((wp, i) => {
      const o = waypointOffset(ln, i, corridors);
      return project(wp.gx + o.x, wp.gy + o.y, wp.plane, cfg);
    });
    const d = points.map(p => `${fmt(p.x)},${fmt(p.y)}`).join(' ');
    out.push(
      `<polyline points="${d}" fill="none" stroke="${ln.color}" ` +
      `stroke-width="${LINE_WIDTH}" stroke-linecap="round" ` +
      `stroke-linejoin="round"/>`
    );
  }

  // stations: stadium for shared-corridor interchanges, circle otherwise
  for (const st of data.stations) {
    const p = project(st.gx, st.gy, st.plane, cfg);
    if (st.kind === 'interchange') {
      const stadium = stadiumForStation(st, corridors, cfg);
      if (stadium) {
        out.push(
          `<g transform="translate(${fmt(stadium.cx)},${fmt(stadium.cy)}) ` +
          `rotate(${fmt(stadium.angle)})">` +
          `<rect x="${fmt(-stadium.length / 2)}" y="${fmt(-INTERCHANGE_R - 1.5)}" ` +
          `width="${fmt(stadium.length)}" height="${fmt(2 * (INTERCHANGE_R + 1.5))}" ` +
          `rx="${fmt(INTERCHANGE_R + 1.5)}" ` +
          `fill="var(--station-fill, #fff)" ` +
          `stroke="var(--station-stroke, #111)" stroke-width="2.4"/></g>`
        );
        for (let s = 0; s < stadium.nTracks; s++) {
          const off = (s - (stadium.nTracks - 1) / 2) * stadium.trackSpacing;
          const dx = stadium.cx + off * stadium.perp.x;
          const dy = stadium.cy + off * stadium.perp.y;
          out.push(
            `<circle cx="${fmt(dx)}" cy="${fmt(dy)}" ` +
            `r="${fmt(INTERCHANGE_R * 0.42)}" ` +
            `fill="var(--station-stroke, #111)"/>`
          );
        }
      } else {
        out.push(
          `<circle cx="${fmt(p.x)}" cy="${fmt(p.y)}" r="${fmt(INTERCHANGE_R + 1.5)}" ` +
          `fill="var(--station-fill, #fff)" stroke="var(--station-stroke, #111)" stroke-width="2.4"/>`
        );
        out.push(
          `<circle cx="${fmt(p.x)}" cy="${fmt(p.y)}" r="${fmt(INTERCHANGE_R * 0.45)}" ` +
          `fill="var(--station-stroke, #111)"/>`
        );
      }
    } else if (st.kind === 'terminal') {
      out.push(
        `<circle cx="${fmt(p.x)}" cy="${fmt(p.y)}" r="${fmt(TERMINAL_R)}" ` +
        `fill="var(--station-fill, #fff)" stroke="var(--station-stroke, #111)" stroke-width="2"/>`
      );
    } else {
      out.push(
        `<circle cx="${fmt(p.x)}" cy="${fmt(p.y)}" r="${fmt(STATION_R)}" ` +
        `fill="var(--station-fill, #fff)" stroke="var(--station-stroke, #111)" stroke-width="1.6"/>`
      );
    }

    const lp = labels.get(st.id);
    if (lp) {
      out.push(
        `<text x="${fmt(lp.x)}" y="${fmt(lp.y)}" font-size="10.5" ` +
        `fill="var(--label-text, #1a1a1a)" text-anchor="${lp.anchor}" ` +
        `font-weight="500">${escapeXml(st.name)}</text>`
      );
    }
  }

  if (opts.showTitle) {
    out.push(
      `<text x="${fmt(minX + 30)}" y="${fmt(minY + 60)}" ` +
      `font-size="34" font-weight="700" fill="#111" letter-spacing="-0.5">` +
      `${escapeXml(opts.title)}</text>`
    );
    out.push(
      `<text x="${fmt(minX + 30)}" y="${fmt(minY + 86)}" font-size="12" ` +
      `fill="#555">${escapeXml(opts.subtitle)}</text>`
    );
  }

  out.push('</svg>');
  return out.join('\n');
}

function fmt(n: number): string {
  return n.toFixed(1);
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
